In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [5]:
y_train = train['count']
X_train = train.drop(['count', 'atemp'], axis=1)
y_test = test['count']
X_test = test.drop(['count', 'atemp'], axis=1)

In [8]:
X_train = np.log1p(X_train)
X_test = np.log1p(X_test)

In [9]:
X_train

,season,holiday,workingday,weather,temp,humidity,windspeed,date,year,month,day,hour,is_night
0,0.693147,0.0,0.0,0.693147,2.383243,4.406719,0.000000,0.000000,7.606885,0.693147,0.693147,0.000000,0.693147
1,0.693147,0.0,0.0,0.693147,2.304583,4.394449,0.000000,0.000000,7.606885,0.693147,0.693147,0.693147,0.693147
2,0.693147,0.0,0.0,0.693147,2.304583,4.394449,0.000000,0.000000,7.606885,0.693147,0.693147,1.098612,0.693147
3,0.693147,0.0,0.0,0.693147,2.383243,4.330733,0.000000,0.000000,7.606885,0.693147,0.693147,1.386294,0.693147
4,0.693147,0.0,0.0,0.693147,2.383243,4.330733,0.000000,0.000000,7.606885,0.693147,0.693147,1.609438,0.693147
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9058,1.386294,0.0,0.0,1.098612,3.304686,4.304065,2.302395,6.391917,7.607381,2.197225,2.995732,2.995732,0.000000
9059,1.386294,0.0,0.0,1.098612,3.304686,4.304065,2.638914,6.391917,7.607381,2.197225,2.995732,3.044522,0.693147
9060,1.386294,0.0,0.0,1.386294,3.274121,4.369448,1.946367,6.391917,7.607381,2.197225,2.995732,3.091042,0.693147
9061,1.386294,0.0,0.0,1.098612,3.274121,4.369448,2.485023,6.391917,7.607381,2.197225,2.995732,3.135494,0.693147
9062,1.386294,0.0,0.0,1.098612,3.274121,4.304065,0.000000,6.391917,7.607381,2.197225,2.995732,3.178054,0.693147

In [11]:
from lightgbm import LGBMRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, mean_squared_log_error

In [40]:
lgb = LGBMRegressor(learning_rate=0.05, n_estimators=100, num_leaves=1000, max_depth=-1, min_child_samples=60)

In [41]:
lgb.fit(X_train, y_train)
pred = lgb.predict(X_test)

train_score = lgb.score(X_train, y_train)
r2 = r2_score(y_test, pred)
mae = mean_absolute_error(y_test, pred)
mse = mean_squared_error(y_test, pred, squared=True)
rmse = mean_squared_error(y_test, pred, squared=False)

print(f'Train r2 score: ', train_score, '\n'
      'Test: ', '\n'
      ' - r2 score: ',  r2, '\n'
      ' - mae: ',  mae, '\n'
      ' - mse: ',  mse, '\n'
      ' - rmse: ',  rmse, '\n'
      )

Train r2 score:  0.961355751126974
Test:
 - r2 score:  0.9065036332252565
 - mae:  45.20635950432297
 - mse:  4342.308098611537
 - rmse:  65.8961918369456